# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

price_option <- function(Expiry, Strike, Spot, Vol, r, NumberOfPaths, alpha, optionType, use_antithetic) {
    .Call(`_MCOptionPricing_price_option`, Expiry, Strike, Spot, Vol, r, NumberOfPaths, alpha, optionType, use_antithetic)
}

rcpp_hello <- function() {
    .Call(`_MCOptionPricing_rcpp_hello`)
}

